# Set by the sanitizer configs in .bazelrc (--define=qwe_sanitizer=...).
config_setting(
    name = "ubsan",
    define_values = {"qwe_sanitizer": "ubsan"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "asan",
    define_values = {"qwe_sanitizer": "asan"},
    visibility = ["//visibility:public"],
)
